server:
  port: ${PORT:8000}
 # contextPath: /auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.145.81.19:1111/eureka/


spring:
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    hibernate:
     ddl-auto: update 
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/inspiratti?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root@123
  application:
    name: auth-server
