
server:
  port: ${PORT:9007}
  

spring:
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    hibernate:
     ddl-auto: update 
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/inspiratti?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  application:
    name: dictionary-service


  #contextPath: /resource
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8000/user
  


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
