
server:
  port: ${PORT:9005}
  

spring:
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    hibernate:
     ddl-auto: update 
  datasource:
    platform: mysql
    url: jdbc:mysql://10.145.81.19:3306/inspiratti?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  application:
    name: media-service

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  #contextPath: /resource
security:
  oauth2:
    resource:
      userInfoUri: http://10.145.81.19:8000/user
  


eureka:
  client:
    serviceUrl:
      defaultZone: http://10.145.81.19:1111/eureka/
      
